package com.elbaroudi.invoice


import java.text.SimpleDateFormat
import java.util.*

object ExportUtils {

    fun invoiceToCSV(invoice: AddFragment.Invoice, language: String): String {
        return buildString {
            append("Field,Value\n")
            append("ID,${invoice.id}\n")
            append("Name,${invoice.name}\n")
            append("Client Name,${invoice.clientName}\n")
            append("Client Phone,${invoice.clientPhone}\n")
            append("Client Email,${invoice.clientEmail}\n")
            append("Client Address,${invoice.clientAddress}\n")
            append("Company Name,${invoice.companyName}\n")
            append("Company Phone,${invoice.companyPhone}\n")
            append("Company Email,${invoice.companyEmail}\n")
            append("Company Address,${invoice.companyAddress}\n")
            append("Total,${invoice.totalAmount}\n")
            append("Currency,${invoice.currency}\n")
            append("Tax,${invoice.taxAmount}\n")
            append("Created At,${SimpleDateFormat("dd/MM/yyyy HH:mm", Locale.getDefault()).format(Date(invoice.createdAt))}\n")
            append("\n${if (language == "ar") "العناصر" else "Items"}:\n")
            append("Name,Quantity,Price,Total\n")
            invoice.items.forEach { item ->
                val itemTotal = item.quantity * item.unitPrice
                append("${item.name},${item.quantity},${item.unitPrice},${"%.2f".format(itemTotal)}\n")
            }
        }
    }

    fun invoiceToText(invoice: AddFragment.Invoice, language: String): String {
        val dateFormat = SimpleDateFormat("dd/MM/yyyy HH:mm", Locale.getDefault())
        val formattedDate = dateFormat.format(Date(invoice.createdAt))

        return buildString {
            append("=" * 50 + "\n")
            append("${if (language == "ar") "فاتورة رقم" else "Invoice"} #${invoice.id}\n")
            append("=" * 50 + "\n")
            append("${if (language == "ar") "اسم الفاتورة" else "Invoice Name"}: ${invoice.name}\n")
            append("${if (language == "ar") "تاريخ الإنشاء" else "Created Date"}: $formattedDate\n\n")

            append("${if (language == "ar") "معلومات العميل" else "Client Information"}:\n")
            append("-" * 30 + "\n")
            append("${if (language == "ar") "الاسم" else "Name"}: ${invoice.clientName}\n")
            append("${if (language == "ar") "الهاتف" else "Phone"}: ${invoice.clientPhone}\n")
            append("${if (language == "ar") "البريد الإلكتروني" else "Email"}: ${invoice.clientEmail}\n")
            append("${if (language == "ar") "العنوان" else "Address"}: ${invoice.clientAddress}\n\n")

            append("${if (language == "ar") "معلومات الشركة" else "Company Information"}:\n")
            append("-" * 30 + "\n")
            append("${if (language == "ar") "الاسم" else "Name"}: ${invoice.companyName}\n")
            append("${if (language == "ar") "الهاتف" else "Phone"}: ${invoice.companyPhone}\n")
            append("${if (language == "ar") "البريد الإلكتروني" else "Email"}: ${invoice.companyEmail}\n")
            append("${if (language == "ar") "العنوان" else "Address"}: ${invoice.companyAddress}\n\n")

            append("${if (language == "ar") "تفاصيل العناصر" else "Item Details"}:\n")
            append("-" * 50 + "\n")
            invoice.items.forEachIndexed { index, item ->
                val itemTotal = item.quantity * item.unitPrice
                append("${index + 1}. ${item.name}\n")
                append("   ${if (language == "ar") "الكمية" else "Quantity"}: ${item.quantity}\n")
                append("   ${if (language == "ar") "السعر" else "Price"}: ${item.unitPrice}\n")
                append("   ${if (language == "ar") "الإجمالي" else "Total"}: ${"%.2f".format(itemTotal)}\n\n")
            }

            append("=" * 50 + "\n")
            if (invoice.taxAmount > 0) {
                val subtotal = invoice.totalAmount / (1 + invoice.taxAmount / 100)
                val taxAmount = invoice.totalAmount - subtotal
                append("${if (language == "ar") "المجموع الفرعي" else "Subtotal"}: ${"%.2f".format(subtotal)} ${invoice.currency}\n")
                append("${if (language == "ar") "الضريبة" else "Tax"} (${invoice.taxAmount}%): ${"%.2f".format(taxAmount)} ${invoice.currency}\n")
            }
            append("${if (language == "ar") "المجموع النهائي" else "Total Amount"}: ${invoice.totalAmount} ${invoice.currency}\n")
            append("=" * 50 + "\n")

            append("\n${if (language == "ar") "شكراً لتعاملكم معنا!" else "Thank you for your business!"}\n")
            append("${if (language == "ar") "تم إنشاء هذه الفاتورة بواسطة تطبيق الفواتير" else "Generated by Invoice App"}\n")
        }
    }

    fun invoiceToQRData(invoice: AddFragment.Invoice, language: String): String {
        return buildString {
            append("${if (language == "ar") "فاتورة" else "Invoice"}: ${invoice.name}\n")
            append("${if (language == "ar") "العميل" else "Client"}: ${invoice.clientName}\n")
            append("${if (language == "ar") "الشركة" else "Company"}: ${invoice.companyName}\n")
            append("${if (language == "ar") "المجموع" else "Total"}: ${invoice.totalAmount} ${invoice.currency}\n")
            append("ID: ${invoice.id}")
        }
    }

    private operator fun String.times(n: Int): String = this.repeat(n)
}